/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package local_project.sparkdemo1_0_1;  
@SuppressWarnings("all")
public class row2StructBeanInfo extends java.beans.SimpleBeanInfo implements java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  private final static Class<row2Struct> currentClass = row2Struct.class;

  public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
          try {
        java.beans.PropertyDescriptor[] list = {
                  new java.beans.PropertyDescriptor("newColumn", currentClass, "getNewColumn", "setNewColumn"),
                };
        return list;
      } catch (java.beans.IntrospectionException iexErr) {
        throw new Error(iexErr.toString());
      }
      }

  public java.beans.BeanDescriptor getBeanDescriptor() {
    java.beans.BeanDescriptor desc = new java.beans.BeanDescriptor(currentClass);
    return desc;
  }
}
