/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package local_project.sparkdemo1_0_1;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class row_tFileInputDelimited_1_HDFSInputFormatStruct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"row_tFileInputDelimited_1_HDFSInputFormatStruct\",\"namespace\":\"local_project.sparkdemo1_0_1\",\"fields\":[{\"name\":\"line\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String line;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return line;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: line = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'line' field.
   */
  public java.lang.String getLine() {
    return line;
  }

  /**
   * Sets the value of the 'line' field.
   * @param value the value to set.
   */
  public void setLine(java.lang.String value) {
    this.line = value;
  }

  /** Creates a new row_tFileInputDelimited_1_HDFSInputFormatStruct RecordBuilder */
  public static local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder newBuilder() {
    return new local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder();
  }
  
  /** Creates a new row_tFileInputDelimited_1_HDFSInputFormatStruct RecordBuilder by copying an existing Builder */
  public static local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder newBuilder(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder other) {
    return new local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder(other);
  }
  
  /** Creates a new row_tFileInputDelimited_1_HDFSInputFormatStruct RecordBuilder by copying an existing row_tFileInputDelimited_1_HDFSInputFormatStruct instance */
  public static local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder newBuilder(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct other) {
    return new local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder(other);
  }
  
  /**
   * RecordBuilder for row_tFileInputDelimited_1_HDFSInputFormatStruct instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<row_tFileInputDelimited_1_HDFSInputFormatStruct>
    implements org.apache.avro.data.RecordBuilder<row_tFileInputDelimited_1_HDFSInputFormatStruct> {

    private java.lang.String line;

    /** Creates a new Builder */
    private Builder() {
      super(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing row_tFileInputDelimited_1_HDFSInputFormatStruct instance */
    private Builder(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct other) {
            super(local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.SCHEMA$);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'line' field */
    public java.lang.String getLine() {
      return line;
    }
    
    /** Sets the value of the 'line' field */
    public local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder setLine(java.lang.String value) {
      validate(fields()[0], value);
      this.line = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'line' field has been set */
    public boolean hasLine() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'line' field */
    public local_project.sparkdemo1_0_1.row_tFileInputDelimited_1_HDFSInputFormatStruct.Builder clearLine() {
      line = null;
      fieldSetFlags()[0] = false;
      return this;
    }


    public row_tFileInputDelimited_1_HDFSInputFormatStruct build() {
      try {
        row_tFileInputDelimited_1_HDFSInputFormatStruct record = new row_tFileInputDelimited_1_HDFSInputFormatStruct();
        record.line = fieldSetFlags()[0] ? this.line : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}